apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-bucket-template-delete
  title: GCP Bucket Templates
  description: Delete a  Bucket on GCP

  tags:
    - gcp
    - infrastructure
    - bucket
    - resource
spec:
  owner: group:sre-team
  type: resource

  parameters:
    - title: Provide some simple information for resource deletion
      required:
        - system
        - lifecycle
        - owner
      properties:
        system:
          title: System
          type: string
          description: System of the component
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System
        # component:
        #   title: Component
        #   type: string
        #   description: Component to create resource
        #   ui:field: EntityPicker
        #   ui:options:
        #     allowedKinds:
        #       - Component
        #     defaultKind: Component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        lifecycle:
          title: Lifecycle
          description: 'Application lifecycle'
          type: string
          default: experimental
          enum:
            - deprecated
            - experimental
            - production


    - title: Infrastructure
      properties:
        env:
          title: Environment
          description: 'Environment to delete resources'
          type: string
          default: dev
          enum:
            - dev
            - stg
            - prd
        bucket:
          title: Bucket Parameters
          type: string
          description: Enter the name for Global GCP Bucket which to be deleted.
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false
  steps:
    - id: fetch-template
      name: Fetch GCP Bucket Templates
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        targetPath: ./gcp-delete
        url: https://github.com/jbbkj-dev/backstage-catalog/tree/main/devxp/skeleton/crossplane/gcp-delete
        values:
          system: ${{ parameters.system }}
          owner: ${{ parameters.owner }}
          env: ${{ parameters.env }}
          bucket: ${{parameters.bucket}}

    - id: open-pr
      name: "Open PR in GitOps Repository"
      action: publish:github:pull-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: github.com?repo=gitops&owner=jatinsharma2132
        branchName: create-${{ parameters.system }}-${{ parameters.env }}-gcp
        title: ':robot: [backstage-bot] Deleted ${{ parameters.system }}-${{ parameters.env }}-${{parameters.bucket}}-gcp'
        description: |
          # New project: ${{ parameters.system }}
          ${{ parameters.description if parameters.description }}
        sourcePath: gcp-delete
        targetPath: apps

    # - id: register
    #   name: Register Application in Catalog
    #   action: catalog:register
    #   if: ${{ parameters.dryRun !== true }}
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info.yaml"


    - name: Results
      if: ${{ parameters.dryRun }}
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Go to GitOps Pull Request
        url: ${{ steps.open-pr.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}